services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads/:/uploads
    env_file:
      - ./env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=afridemia

volumes:
  postgres_data:
