services:
  web:
    image: nginx:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /media:/media
    env_file:
      - ./env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=afridemia
    ports:
      - 8432:5432

volumes:
  postgres_data:
