services:
# -----------------------afridemia datatbase setup---------------------
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=afridemia
    ports:
      - 8432:5432

# -----------------------afridemia web app setup---------------------
  web:
    build: 
      context: .
    volumes:
      - ./static:/static
    env_file:
      - ./env
    ports:
      - "8000:8000"
    depends_on:
      - db

# -----------------------NGINX setup---------------------
  nginx:
    build: ./nginx
    volumes:
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: