# Generated by Django 4.2 on 2023-05-13 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(default='', max_length=255)),
                ('cel', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('moto', models.CharField(blank=True, max_length=255, null=True)),
                ('year_founded', models.CharField(blank=True, max_length=4, null=True)),
                ('mgt_quote', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ad_copy', models.TextField(blank=True, null=True)),
                ('resumption', models.CharField(blank=True, default='', max_length=180, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('time_range', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.CharField(blank=True, max_length=255, null=True)),
                ('success_rate', models.IntegerField(blank=True, default='0', null=True)),
                ('professors', models.IntegerField(blank=True, default='0', null=True)),
                ('students', models.IntegerField(blank=True, default='0', null=True)),
                ('formations', models.IntegerField(blank=True, default='0', null=True)),
                ('divisions', models.IntegerField(blank=True, default='0', null=True)),
                ('systems', models.IntegerField(blank=True, default='0', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='schools/thumbnails')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='schools/banners')),
                ('crest', models.ImageField(blank=True, null=True, upload_to='schools/crests')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('levels', models.ManyToManyField(blank=True, null=True, to='schools.educationlevel')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/teachers')),
                ('fullname', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Prof.', 'Prof.'), ('Doc.', 'Doc.'), ('Mr.', 'M.'), ('Mrs.', 'Mme'), ('Ms.', 'Mlle')], default='', max_length=50)),
                ('subjects', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField(default='0')),
                ('qualifications', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/laboratories')),
                ('genre', models.CharField(choices=[('lab', 'Laboratoire'), ('lib', 'Bibliotheque'), ('can', 'Cantine'), ('gym', 'Espace de sport'), ('pool', 'Piscine')], default='', max_length=50)),
                ('label', models.CharField(default='image label', max_length=255)),
                ('maxseats', models.IntegerField(default='0')),
                ('info', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='year', max_length=4)),
                ('pass_rate', models.IntegerField(default='0')),
                ('fail_rate', models.IntegerField(default='0')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/photos')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/classrooms')),
                ('name', models.CharField(default='', max_length=255)),
                ('fee', models.IntegerField(blank=True, default='0', null=True)),
                ('size', models.IntegerField(blank=True, default='0', null=True)),
                ('maxseats', models.IntegerField(blank=True, default='0', null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/reports')),
                ('title', models.CharField(default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(default='avantage', max_length=255)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
