# Generated by Django 4.2 on 2023-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
