# Generated by Django 4.2 on 2023-05-15 14:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_country_alter_school_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
