# Generated by Django 4.2 on 2023-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='levels'),
        ),
    ]
