# Generated by Django 4.1.9 on 2023-08-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_rename_thumbnail_educationlevel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='resumption',
        ),
        migrations.AddField(
            model_name='school',
            name='resumption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
