# Generated by Django 4.1.9 on 2023-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_remove_school_resumption_school_resumption_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='school',
            name='time_range',
        ),
        migrations.AddField(
            model_name='school',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
