# Generated by Django 4.1.9 on 2023-08-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_school_availability_remove_school_time_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='divisions',
            new_name='formation_count',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='formations',
            new_name='student_count',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='professors',
            new_name='tearcher_count',
        ),
        migrations.RemoveField(
            model_name='school',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='school',
            name='students',
        ),
        migrations.RemoveField(
            model_name='school',
            name='systems',
        ),
    ]
