# Generated by Django 4.1 on 2023-08-07 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0011_faculty_serie_rename_date_posted_article_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreInscription',
            new_name='PreRegistration',
        ),
    ]
