# Generated by Django 4.1 on 2023-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_cursus_faculty_school_school_pedagogy'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='genre',
            field=models.CharField(choices=[('canteen', 'Cantine'), ('gym', 'Espace de sport'), ('laboratory', 'Laboratoire'), ('library', 'Bibliotheque'), ('pool', 'Piscine'), ('playground', 'Cour de récréation'), ('infirmary', 'Infirmerie')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='structure',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
