# Generated by Django 4.1 on 2023-08-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_remove_preregistration_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='tearcher_count',
            new_name='teacher_count',
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='last_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
