# Generated by Django 4.1 on 2023-08-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_rename_tearcher_count_school_teacher_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=255)),
                ('pass_rate', models.FloatField(default='0')),
                ('candidates', models.IntegerField(default='0')),
                ('year', models.CharField(default='year', max_length=4)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.AddField(
            model_name='cursus',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
