# Generated by Django 4.1 on 2023-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_examstat_cursus_school_delete_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='schools/crests'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
