# Generated by Django 4.1 on 2023-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_school_certificate_school_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
