# Generated by Django 4.1 on 2023-08-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_school_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tel',
        ),
    ]
