# Generated by Django 4.1 on 2023-08-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_remove_teacher_instagram_link_remove_teacher_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='years_of_experience',
            new_name='xp',
        ),
    ]
