# Generated by Django 4.1 on 2023-08-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_rename_years_of_experience_teacher_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='maxseats',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='schoolarticle',
            name='subtitle',
        ),
    ]
