# Generated by Django 4.1 on 2023-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_rename_maxseats_structure_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstat',
            name='fail_rate',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='examstat',
            name='pass_rate',
            field=models.IntegerField(default='0'),
        ),
    ]
