# Generated by Django 4.1 on 2023-08-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_examstat_fail_rate_alter_examstat_pass_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='classroom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
