# Generated by Django 4.1 on 2023-08-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_alter_preregistration_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='schools/gallerie')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.RenameModel(
            old_name='ExamStat',
            new_name='Performance',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
