# Generated by Django 4.1 on 2023-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_gallery_rename_examstat_performance_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='genre',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='school',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='schools/cerificate'),
        ),
    ]
