# Generated by Django 4.1 on 2023-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
    ]
