# Generated by Django 4.1 on 2023-08-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_rename_text_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
