# Generated by Django 4.1 on 2023-09-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_alter_classroom_image_alter_department_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='telegram',
        ),
    ]
