# Generated by Django 4.1 on 2023-09-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0036_rename_mgt_quote_school_quote_alter_school_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='school',
            name='success_rate',
        ),
    ]
