# Generated by Django 4.1 on 2023-09-29 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_rename_xp_teacher_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='fail_rate',
        ),
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='year',
            field=models.CharField(default='year', max_length=4),
        ),
        migrations.AddField(
            model_name='performance',
            name='classroom',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='highest',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='performance',
            name='lowest',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('-----', '-----'), ('canteen', 'Cantine'), ('gym', 'Espace de sport'), ('laboratory', 'Laboratoire'), ('library', 'Bibliotheque'), ('pool', 'Piscine'), ('playground', 'Cour de récréation'), ('infirmary', 'Infirmerie')], default='', max_length=50),
        ),
    ]
