# Generated by Django 4.1 on 2023-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='type',
        ),
        migrations.AddField(
            model_name='advert',
            name='target',
            field=models.CharField(blank=True, choices=[('schools', 'Ecoles'), ('tutors', 'Enseignants')], default='', max_length=50, null=True),
        ),
    ]
