# Generated by Django 4.1 on 2023-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_advert_message_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
