# Generated by Django 4.1 on 2023-09-26 15:28

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_remove_school_quote_remove_school_success_rate'),
        ('base', '0015_alter_blogpost_image_alter_subject_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='years_of_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='tel',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='cel',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='tutor',
            name='certificate',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='tutors'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='levels',
            field=models.ManyToManyField(to='schools.educationlevel'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualification',
            field=models.CharField(choices=[('BAC', 'BAC'), ('BAC + 1', 'BAC + 1'), ('BAC + 2', 'BAC + 2'), ('BAC + 3', 'BAC + 3'), ('BAC + 4', 'BAC + 4'), ('BAC + 5', 'BAC + 5'), ('BAC + 6', 'BAC + 6'), ('BAC + 7', 'BAC + 7')], default='BAC', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='title',
            field=models.CharField(choices=[('Prof.', 'Prof.'), ('Doc.', 'Doc.'), ('M.', 'M.'), ('Mme.', 'Mme'), ('Mlle.', 'Mlle')], default='', max_length=50),
        ),
    ]
