# Generated by Django 4.1 on 2023-09-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_tutor_civility_alter_tutor_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='title',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='civility',
            field=models.CharField(choices=[('M.', 'M.'), ('Mme.', 'Mme.'), ('Mlle.', 'Mlle.')], default='', max_length=50),
        ),
    ]
