# Generated by Django 4.1 on 2023-09-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_blogpost_image_alter_blogpost_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
